config/routes.rb
Rails.application.routes.draw do

  root to: 'fagrids#index'
  get 'fagrids/search'
  get 'fagrids/sort'
  resources :fagrids, only: [:index, :new, :create, :show] do
    collection do
      get 'msearch'
    end
  end
end

app/models/fagrid.rb
class Fagrid < ApplicationRecord
  has_one_attached :image
  has_many :fagrid_member
  has_many :members, through: :fagrid_member

  extend ActiveHash::Associations::ActiveRecordExtensions
  belongs_to :quest
  belongs_to :attr
  belongs_to :job
  belongs_to :ex_ability
  belongs_to :limit_ability
  belongs_to :main_summon
  belongs_to :seraphic
  belongs_to :atk_arculm
  belongs_to :hp_arculm
  belongs_to :difficulty
  belongs_to :time_about
end

app/controllers/fagrids_controller.rb
class FagridsController < ApplicationController

  def index
    @fagrids = Fagrid.order(id: "DESC")
  end

  def new
    session[:new_fagrid] = nil
    @fullauto_member = FullautoMember.new(session[:new_fagrid] || {})
  end

  def create
    @fullauto_member = FullautoMember.new(fagrid_params)
    if @fullauto_member.valid?
      @fullauto_member.save
      redirect_to root_path
    else
      session[:new_fagrid] = fagrid_params.to_hash # *2 フォームで渡された値のみ保存
      flash[:danger] = @fullauto_member.errors.full_messages
      redirect_to new_fagrid_path
    end
  end

  def show
    @fagrid = Fagrid.find(params[:id])
    @fagrids = Fagrid.all

  end

  def search
    search_grid
    @fagrids = Fagrid.order(id: "DESC")
  end

  def sort
    search_grid
    @result = @g.result    # 検索条件にマッチした商品の情報を取得
  end

  # メンバー検索用
  def msearch 
    members = Member.where(['member LIKE ?', "%#{params[:keyword]}%"]).pluck(:member)
    render json: members
  end

  private
  
  def fagrid_params
    params.require(:fullauto_member).permit(:image, :quest_id, :attr_id, :job_id, :ex_ability_id, :ex_ability2_id, :limit_ability_id, :limit_ability2_id,
      :member, :member2, :member3, :member4, :member5, :main_summon_id, :seraphic_id, :atk_arculm_id, :hp_arculm_id, :difficulty_id, :time_about_id, :remark)
  end
  
  def search_grid
    @g = Fagrid.ransack(params[:q]) # 検索オブジェクトを生成
  end

end

app/helpers/fagrids_helper.rb
module FagridsHelper
end

app/views/fagrids/_ability_selector.html.erb
<%= f.collection_select(:ex_ability_id, ExAbility.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"ex-ability"}) %>
<select class="select-box" id="limit-ability" name="fagrid_member[limit_ability_id]">
  <option value="" >---</option>
</select>

<%= f.collection_select(:ex_ability2_id, ExAbility.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"ex-ability2", style: "display: none;"}) %>

<select class="select-box" id="limit-ability2", style="display: none;" , name="fagrid_member[limit_ability2_id]">
  <option value="" >---</option>
</select>

app/views/fagrids/index.html.erb
<link href="https://fonts.googleapis.com/css?family=Noto+Sans+JP&display=swap" rel="stylesheet">
<main role="main">

  <section class="jumbotron text-center">
    <div class="container">
      <!-- <h1 class="jumbotron-heading">Album example</h1> -->
      <h1 class="jumbotron-heading">フルオート編成</h1>
      <!-- <p class="lead text-muted">Something short and leading about the collection below—its contents, the creator, etc. Make it short and sweet, but not too short so folks don't simply skip over it entirely.</p> -->
      <p class="lead text-muted">フルオートで使っている編成を共有しよう</p>
      <p>
        <!-- <a href="#" class="btn btn-primary my-2">Main call to action</a> -->
        <%= link_to '投稿する', new_fagrid_path, class: "btn btn-primary my-2"%>
        <!-- <a href="#" class="btn btn-secondary my-2">Secondary action</a> -->
        <%= link_to '検索する', fagrids_search_path, class: "btn btn-secondary my-2"%>
      </p>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
    
      <div class="row">
      <% @fagrids.each do |fagrid| %>
        <div class='col-md-4 grid-card'>
          <div class="card mb-4 shadow-sm">
          <%= link_to fagrid_path(fagrid.id) do %>
            <%= image_tag fagrid.image, class: "card-img-top grid-img" %>
          <% end %>
            <div class="card-body">
              <h4 class="card-title"><%= fagrid.quest.name %></h4>
              <small class="card-text text-muted">自石：</small><h6 class="card-text"><%= fagrid.main_summon.name %>(<%= fagrid.attr.name %>)</h6>
              <small class="card-text text-muted">ジョブ：</small><h6 class="card-text"><%= fagrid.job.name %></h6>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">見る</button> %>
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">編集</button> %>
                </div>
                <small class="text-muted">投稿日時：<%= l fagrid.created_at, format: :short %></small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>

</main>

app/views/fagrids/new.html.erb
<div class="items-sell-contents">
  <%# <header class="items-sell-header">
    <%= link_to image_tag('furima-logo-color.png' , size: '185x50'), "/" %>

  <%# </header> %>
  <div class="items-sell-main">
    <h2 class="items-sell-title">編成の情報を入力</h2>
    <%= form_with model: @fullauto_member, url: fagrids_path, local: true do |f| %>

    <%# インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>
    <% flash.each do |message_type, messages| %>
      <% messages.each do |message| %>
        <div class="alert alert-<%= message_type %>"><%= message %></div>
      <% end %>
    <% end %>
    <%# //インスタンスを渡して、エラー発生時にメッセージが表示されるようにしましょう。%>

    <%# 装備画像 %>
    <div class="img-upload">
      <div class="weight-bold-text">
        装備画像
        <span class="indispensable">必須</span>
      </div>
      <div id="image-list"></div>
      <div class="click-upload">
        <p>
          クリックしてファイルをアップロード
        </p>
        <%= f.file_field :image %>
      </div>
    </div>
    <%# /装備画像 %>

    <%# 戦闘概要 %>
    <div class="items-detail">
      <%# <div class="weight-bold-text">詳細</div> %>
      <div class="form">
        <div class="weight-bold-text">
          対戦相手
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:quest_id, Quest.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"quest"}) %>
        <div class="weight-bold-text">
          主人公の属性
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:attr_id, Attr.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"attr"}) %>
        <div class="weight-bold-text">
          主人公のジョブ
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:job_id, Job.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"job"}) %>
        <div class="weight-bold-text">
          主人公のアビリティ
          <span class="indispensable">必須</span>
        </div>
        <%# アビリティ選択 %>
        <%= render partial: 'ability_selector', locals: { f: f} %>
        <%# /レンダリング %>
      </div>
    </div>
    <%# /戦闘概要 %>

    <%# バトルメンバー %>
    <div class="new-items">
      <div class="weight-bold-text">
        バトルメンバー
      </div>
      <%= f.text_field :member, class:"member-name js-member", id:"member1-name", placeholder:"キャラクター名", maxlength:"20" %>
      <%= f.text_field :member2, class:"member-name js-member", id:"member2-name", placeholder:"キャラクター名", maxlength:"20" %>
      <%= f.text_field :member3, class:"member-name js-member", id:"member3-name", placeholder:"キャラクター名", maxlength:"20" %>
      <%= f.text_field :member4, class:"member-name js-member", id:"member4-name", placeholder:"キャラクター名", maxlength:"20" %>
      <%= f.text_field :member5, class:"member-name js-member", id:"member5-name", placeholder:"キャラクター名", maxlength:"20" %>
    </div>
    <%#/ バトルメンバー %>

    <%# 召喚石について %>
    <div class="items-detail">
      <%# <div class="weight-bold-text question-text">
        <span>召喚石</span>
        <a class="question" href="#">?</a>
      </div> %>
      <div class="form">
        <div class="weight-bold-text">
          メイン召喚石
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:main_summon_id, MainSummon.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"main-summon"}) %>
        <div class="weight-bold-text">
          天司石
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:seraphic_id, Seraphic.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"seraphic"}) %>
        <div class="weight-bold-text">
          アーカルム石
          <span class="indispensable">必須</span>
        </div>
        <%= f.collection_select(:atk_arculm_id, AtkArculm.all, :id, :name, {include_blank: "攻撃"}, {class:"select-box", id:"atk-arculm"}) %>
        <%= f.collection_select(:hp_arculm_id, AtkArculm.all, :id, :name, {include_blank: "HP"}, {class:"select-box", id:"hp-arculm"}) %>
      </div>
    </div>
    <%# /召喚石について %>

    <%# その他 %>
    <div class="new-items">
      <div class="items-explain">
        <div class="weight-bold-text">
          備考欄
        </div>
      <%= f.text_area :remark, class:"remark", id:"remark", placeholder:"当てはまらなかったものがある場合や、予備アクションなどがあればこちらに記載してください（始めに何かアビリティを使う、召喚石を使う等）", maxlength:"500" %>
      </div>
      <div class="weight-bold-text">
        終末武器
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:difficulty_id, Difficulty.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"difficulty"}) %>
      <div class="weight-bold-text">
        参考タイム
        <span class="indispensable">必須</span>
      </div>
      <%= f.collection_select(:time_about_id, TimeAbout.all, :id, :name, {include_blank: "---"}, {class:"select-box", id:"time-about"}) %>
    </div>
    <%#/ その他 %>

    <%# 下部ボタン %>
    <div class="sell-btn-contents">
      <%= f.submit "投稿する" ,class: "btn btn-primary my-2" %>
      <%= link_to '戻る', root_path, class: "btn btn-secondary my-2"%>
    </div>
    <%# /下部ボタン %>
  </div>
  <% end %>
</div>
<%= javascript_pack_tag 'grid/application' %>

app/views/fagrids/search.html.erb
<main role="main">
  <section class="jumbotron text-center">
    <div class="container">
      <h1 class="jumbotron-heading">編成を検索する</h1>
      <%= search_form_for @g, url: fagrids_sort_path do |f| %>
        <%= f.label :quest_id_eq, 'バトル' %>
        <%= f.collection_select :quest_id_eq, Quest.all, :id, :name, include_blank: '指定なし' %>
        <%= f.label :quest_id_eq, '主人公の属性' %>
        <%= f.collection_select :attr_id_eq, Attr.all, :id, :name, include_blank: '指定なし' %>
        <%= f.label :quest_id_eq, 'メイン石' %>
        <%= f.collection_select :main_summon_id_eq, MainSummon.all, :id, :name, include_blank: '指定なし' %>
        <%= f.label :quest_id_eq, '討伐時間' %>
        <%= f.collection_select :time_about_id_eq, TimeAbout.all, :id, :name, include_blank: '指定なし' %>
        <br>
        <%= f.label :difficulty_id, '終末', class: "search-title" %>
        <%= f.radio_button :difficulty_id_eq, '2' %> 
        5凸
        <%= f.radio_button :difficulty_id_eq, '3' %> 
        4凸
        <%= f.radio_button :difficulty_id_eq, '4' %> 
        ドラポン
        <%= f.radio_button :difficulty_id_eq, '' %> 
        指定無し
        <br>
        <%= f.submit '検索' %>
      <% end %>
    </div>
  </section>

  <div class="album py-5 bg-light">
    <div class="container">
      <div class="row">
      <% @fagrids.each do |fagrid| %>
        <div class='col-md-4'>
          <div class="card mb-4 shadow-sm">
          <%= link_to fagrid_path(fagrid.id) do %>
            <%= image_tag fagrid.image, class: "card-img-top grid-img" %>
          <% end %>
            <div class="card-body">
              <h4 class="card-title"><%= fagrid.quest.name %></h4>
              <p class="card-text"><%= fagrid.main_summon.name %>(<%= fagrid.attr.name %>)　<%= fagrid.job.name %></p>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">見る</button>
                  <button type="button" class="btn btn-sm btn-outline-secondary">編集</button> %>
                </div>
                <small class="text-muted">投稿日時：<%= l fagrid.created_at, format: :short %></small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
      </div>
    </div>
  </div>

</main>

app/views/fagrids/show.html.erb
<div class="item-show">
  <div class="item-box">
    <h2 class="name">
      <%= @fagrid.quest.name %>
    </h2>
    <div class='item-img-content'>
      <%= image_tag @fagrid.image, class:"item-box-img" %>
    </div>

    <div class="item-explain-box">
      <span><%= @fagrid.remark %></span>
    </div>
    <table class="detail-table">
      <tbody>
        <tr>
          <th class="detail-item">ジョブ</th>
          <td class="detail-value"><%= @fagrid.job.name %></td>
        </tr>
        <tr>
          <th class="detail-item">アビリティ</th>
          <td class="detail-value"><%= @fagrid.ex_ability.name %>　<%= @fagrid.limit_ability.name %></td>
        </tr>
        <tr>
          <th class="detail-item">バトルメンバー</th>
          <td class="detail-value">
          <% @fagrid.members.each do |member|%>
            <%= member.member %>
          <% end %>
          </td>
        </tr>
      </tbody>
    </table>
    <table class="table table-bordered">
      <thead>
        <tr>
          <th scope="col">メイン石</th>
          <th scope="col">天司石</th>
          <th scope="col">アーカルム石(与ダメ)</th>
          <th scope="col">アーカルム石(HP)</th>
          <th scope="col">終末</th>
          <th scope="col">所要時間</th>
        </tr>
      </thead>
      <tbody>
        <tr>
          <td><%= @fagrid.main_summon.name %></td>
          <td><%= @fagrid.seraphic.name %></td>
          <td><%= @fagrid.atk_arculm.name %></td>
          <td><%= @fagrid.hp_arculm.name %></td>
          <td><%= @fagrid.difficulty.name %></td>
          <td><%= @fagrid.time_about.name %></td>
        </tr>
      </tbody>
    </table>
</div>

app/views/fagrids/sort.html.erb
<section class="jumbotron text-center">
  <div class="container">
    <h1 class="jumbotron-heading text-center">検索結果</h1>
  </div>
  <%= link_to '検索画面に戻る', fagrids_search_path%>
</section>
<div class="album py-5 bg-light">
  <div class="container">
    <div class="row">
    <% if @result.length != 0 %>
      <% @result.each do |fagrid| %>
        <div class='col-md-4'>
          <div class="card mb-4 shadow-sm">
          <%= link_to fagrid_path(fagrid.id) do %>
            <%= image_tag fagrid.image, class: "card-img-top grid-img" %>
          <% end %>
            <div class="card-body">
              <h4 class="card-title"><%= fagrid.quest.name %></h4>
              <small class="card-text text-muted">自石：</small><h6 class="card-text"><%= fagrid.main_summon.name %>(<%= fagrid.attr.name %>)</h6>
              <small class="card-text text-muted">ジョブ：</small><h6 class="card-text"><%= fagrid.job.name %></h6>
              <div class="d-flex justify-content-between align-items-center">
                <div class="btn-group">
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">見る</button> %>
                  <%# <button type="button" class="btn btn-sm btn-outline-secondary">編集</button> %>
                </div>
                <small class="text-muted">投稿日時：<%= l fagrid.created_at, format: :short %></small>
              </div>
            </div>
          </div>
        </div>
      <% end %>
    <% else %>
      <h1>該当無し</h1>
      <%= link_to '投稿する', new_fagrid_path, class: "btn btn-primary my-2"%>
    <% end %>
    </div>
  </div>
</div>